#!/usr/bin/env ruby
RAILS_ENV = 'development'
require File.dirname(__FILE__) + '/../config/environment.rb'

class MailFetcherDaemon < Daemon::Base
  ActiveRecord::Base.connection.reconnect!
  @config = YAML.load_file("#{RAILS_ROOT}/config/mail.yml")
  @config = @config[RAILS_ENV].to_options
  
  @sleep_time = @config.delete(:sleep_time) || 60
  @already_tried = false
  def self.start
    puts "Starting MailFetcherDaemon"
    # Add your own receiver object below
    @options = {:receiver => MailProcessor}.merge(@config)
    @fetcher = Fetcher.create(@options)
    
    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end


  end
  
  def self.stop
    puts "Stopping MailFetcherDaemon"
  end
  
end

MailFetcherDaemon.daemonize
